default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: rigel_development

test:
  <<: *default
  database: rigel_test

production:
  <<: *default
  database: rigel_production
  username: <%= ENV["RIGEL_DATABASE_USERNAME"] %>
  password: <%= ENV["RIGEL_DATABASE_PASSWORD"] %>
