version: '3.8'

services:
  server:
    environment:
      - RAILS_ENV=production
      - BUNDLE_WITHOUT=development:test
    ports:
      - "80:3000"
    restart: unless-stopped

  agent:
    build: ./agent
    environment:
      - NODE_ENV=production
    ports:
      - "443:4000"
    restart: unless-stopped 