version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: docker/dev.server.Dockerfile
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_APP_CONFIG=/rails/.bundle
    volumes:
      - ../server:/rails:cached
      - bundler_gems:/usr/local/bundle
    ports:
      - "3000:3000"
    command: bash -c "
      while ! nc -z redis 6379; do
        echo 'Waiting for Redis to be ready...';
        sleep 1;
      done;
      while ! nc -z db 5432; do
        echo 'Waiting for PostgreSQL to be ready...';
        sleep 1;
      done;
      rm -f tmp/pids/server.pid;
      bundle exec rails db:prepare;
      bundle exec rails server -b 0.0.0.0"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - rigel-network

  agent:
    build: 
      context: ../agent
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../agent:/app:cached
      - /app/node_modules
    ports:
      - "4000:4000"
      - "3001:3001"
    depends_on:
      - server
    networks:
      - rigel-network
    tty: true
    stdin_open: true

volumes:
  bundler_gems:

networks:
  rigel-network:
    name: rigel-network 